In [3]:
# sort
import numpy as np
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[22, 72, 83,  9],
       [46, 97, 97, 14],
       [16, 41, 17, 87],
       [22,  9, 43, 33],
       [68, 34, 46, 53],
       [54, 22, 52, 99]])

In [5]:
np.sort(a)

array([[ 9, 22, 72, 83],
       [14, 46, 97, 97],
       [16, 17, 41, 87],
       [ 9, 22, 33, 43],
       [34, 46, 53, 68],
       [22, 52, 54, 99]])

In [13]:
np.sort(a,axis=0)[::-1]

array([[68, 97, 97, 99],
       [54, 72, 83, 87],
       [46, 41, 52, 53],
       [22, 34, 46, 33],
       [22, 22, 43, 14],
       [16,  9, 17,  9]])

In [11]:
# for descending
np.sort(a)[::-1]

array([[22, 52, 54, 99],
       [34, 46, 53, 68],
       [ 9, 22, 33, 43],
       [16, 17, 41, 87],
       [14, 46, 97, 97],
       [ 9, 22, 72, 83]])

In [40]:
# append axis colum
value=np.array([[2,34,6,8],[4,5,7,8]])
x=np.append(a,value,axis=0)


array([[22, 72, 83,  9],
       [46, 97, 97, 14],
       [16, 41, 17, 87],
       [22,  9, 43, 33],
       [68, 34, 46, 53],
       [54, 22, 52, 99],
       [ 2, 34,  6,  8],
       [ 4,  5,  7,  8]])

In [42]:
# append axis row
value2=np.array([[1,],[1],[1],[1],[1],[1]])
y=np.append(a,value2, axis=1)
y

array([[22, 72, 83,  9,  1],
       [46, 97, 97, 14,  1],
       [16, 41, 17, 87,  1],
       [22,  9, 43, 33,  1],
       [68, 34, 46, 53,  1],
       [54, 22, 52, 99,  1]])

In [79]:
# concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
# np.vstack((c,d))
np.concatenate((c,d), axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
# np.hstack((c,d))
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [111]:
# unique
e=np.array([1,1,1,2,2,3,3,1,2,3,4,5,4,5])
f=np.array([[11,23,54,11,23,1,2,1,2,3,3],[1,2,3,4,1,2,3,4,7,8,100]])
np.unique(f).shape
np.unique(e).size



5

In [117]:
z=np.random.randint(1,100,12)
z

array([58, 32,  2, 16, 78, 52, 47, 40, 51, 26, 31, 71])

In [123]:
# where
indices=np.where(z>50)
indices

(array([ 0,  4,  5,  8, 11], dtype=int64),)

In [125]:
z[indices]

array([58, 78, 52, 51, 71])

In [137]:
# np.where(condition,true,false)
np.where(z>40,"yes","no")

array(['yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no',
       'no', 'yes'], dtype='<U3')

In [139]:
np.where(z%2==0,0,z)

array([ 0,  0,  0,  0,  0,  0, 47,  0, 51,  0, 31, 71])

In [141]:
# argmax
print(z)
print(np.argmax(z))

[58 32  2 16 78 52 47 40 51 26 31 71]
4


In [151]:
np.argmax(a,axis=0)

array([4, 1, 1, 5], dtype=int64)

In [147]:
print(a)

[[22 72 83  9]
 [46 97 97 14]
 [16 41 17 87]
 [22  9 43 33]
 [68 34 46 53]
 [54 22 52 99]]


In [173]:
# cumsum, cumpord
g=np.ones((7,4))
np.cumsum(g, axis=0)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [179]:
np.cumprod(a)

array([         22,        1584,      131472,     1183248,    54429408,
         984685280,  1025191648,  1467781184,  2009662464,   791782400,
         575398912, -1479902208,  1801889792,  -962861056,  1546647552,
        -500238336,   343531520, -1204830208,   412385280,   381583360,
        -869335040, -1945501696,  1913126912,   421003264])

In [187]:
z

array([58, 32,  2, 16, 78, 52, 47, 40, 51, 26, 31, 71])

In [193]:
# histogram
np.histogram(z,bins=[10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 2, 2, 3, 0, 2, 0, 0], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [197]:
# isin
items=[58,40,50,20]
z[np.isin(z,items)]

array([58, 40])

In [209]:
# flip
np.flip(a,axis=0)


array([[54, 22, 52, 99],
       [68, 34, 46, 53],
       [22,  9, 43, 33],
       [16, 41, 17, 87],
       [46, 97, 97, 14],
       [22, 72, 83,  9]])

In [221]:
z

array([ 100, 1029,    2,   16,   78,   52,   47,   40,   51,   26,   31,
         71])

In [219]:
# put
x=np.put(z,[0,1],[100,1029])


In [223]:
# delete
np.delete(z,[0,1])

array([ 2, 16, 78, 52, 47, 40, 51, 26, 31, 71])

In [227]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [229]:
# intersection
np.intersect1d(m,n)

array([3, 4, 5])

In [233]:
# /difference
np.setdiff1d(n,m)

array([6, 7])

In [235]:
# /setxor
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [239]:
np.in1d(n,m)

array([ True,  True,  True, False, False])