In [3]:
# creating numpy array
import numpy as np
a=np.array([1,2,43,32])
print(type(a))

<class 'numpy.ndarray'>


In [11]:
# 2d and 3d
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [21]:
# np.arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [27]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
# np.zeros
np.zeros((100,100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [49]:
# np.random
np.random.random((10,2))

array([[0.56389847, 0.26498026],
       [0.98039273, 0.1828905 ],
       [0.95074525, 0.10329155],
       [0.99135348, 0.16929746],
       [0.75866867, 0.51450261],
       [0.11892208, 0.96533442],
       [0.38015875, 0.31479309],
       [0.23979976, 0.46374358],
       [0.32974531, 0.1153556 ],
       [0.53489584, 0.83387799]])

In [69]:
np.random.randint(1,9, size=((4,20)))

array([[1, 5, 6, 5, 2, 6, 3, 3, 5, 4, 1, 4, 1, 7, 1, 1, 2, 3, 7, 4],
       [8, 8, 8, 1, 6, 2, 5, 8, 1, 1, 3, 4, 6, 4, 3, 2, 8, 2, 6, 1],
       [8, 2, 3, 5, 7, 1, 1, 1, 1, 8, 6, 2, 8, 6, 2, 1, 3, 6, 6, 4],
       [4, 8, 1, 7, 5, 2, 2, 7, 8, 2, 6, 2, 2, 7, 5, 1, 6, 3, 2, 5]])

In [77]:
# np.linspace
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [83]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array attributes

In [95]:
a1=np.arange(10)
a2=np.arange(12, dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [97]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [99]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [101]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [107]:
# itemsize
a3.itemsize

4

In [109]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [125]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [173]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
# scalar operations
# arithmetic
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [147]:
# relational
a1*2 == 2

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [149]:
# vector operations
# arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [159]:
# max/min/sum/product
np.max(a2, axis=1)

array([15, 19, 23])

In [163]:
# mean/median/std/var
np.mean(a1, axis=1)

array([1.5, 5.5, 9.5])

In [167]:
# Trigonometric
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [189]:
# dot product
import numpy as np

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [193]:
# log and exponents
np.log(a3)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [195]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [207]:
# ROUND/FLOOR/CEIL
a=np.random.random((3,4))*100
np.ceil(a)

array([[51., 92., 31., 72.],
       [46., 10., 57.,  1.],
       [10., 65., 40., 77.]])


Indexing and slicing


In [216]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [220]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [228]:
a3[0,1,0]

2

In [230]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
a1[2:5]

array([2, 3, 4])

In [234]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [236]:
a2[0,:]

array([0, 1, 2, 3])

In [242]:
a2[:,2]

array([ 2,  6, 10])

In [248]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [254]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [260]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [264]:
a2[1:2, 0::3]

array([[4, 7]])

In [268]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [270]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [276]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [282]:
a3[1:2]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [284]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [290]:
a3[0,1,:]

array([3, 4, 5])

In [298]:
a3[1,:,1]

array([10, 13, 16])

In [304]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [308]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [314]:
# iterating
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [320]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [334]:
for i in a3:
    for j in i:
        for k in j:
            # print(k)

In [336]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [340]:
# ravel
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [347]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [349]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [351]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [361]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [367]:
# vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]